# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alexaUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Alexa(object):
    def setupUi(self, Alexa):
        Alexa.setObjectName("Alexa")
        Alexa.resize(319, 508)
        self.centralwidget = QtWidgets.QWidget(Alexa)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 321, 511))
        self.label.setStyleSheet(
            "background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0))")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resources/avatar.png"))
        self.label.setScaledContents(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(100, 440, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setStyleSheet("background: rgb(85, 170, 255)")
        self.start.setObjectName("start")
        self.terminate = QtWidgets.QPushButton(self.centralwidget)
        self.terminate.setEnabled(True)
        self.terminate.setGeometry(QtCore.QRect(100, 480, 89, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.terminate.setFont(font)
        self.terminate.setStyleSheet("background: rgb(170, 0, 255)")
        self.terminate.setObjectName("terminate")
        Alexa.setCentralWidget(self.centralwidget)

        self.retranslateUi(Alexa)
        QtCore.QMetaObject.connectSlotsByName(Alexa)

    def retranslateUi(self, Alexa):
        _translate = QtCore.QCoreApplication.translate
        Alexa.setWindowTitle(_translate("Alexa", "MainWindow"))
        self.start.setText(_translate("Alexa", "start"))
        self.terminate.setText(_translate("Alexa", "terminate"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Alexa = QtWidgets.QMainWindow()
    ui = Ui_Alexa()
    ui.setupUi(Alexa)
    Alexa.show()
    sys.exit(app.exec_())
